### ISSUE TITLE
small issue with Name taging

### ISSUE THREAD

**Issue by pasea** [cmachler/aws-lambda-ebs-backups#1]
I noticed if you use this to make backup of multiple volumes,  it adds same mount point name for all backups.  For example if first volume it takes snapshots is /dev/xvda all others will have same in the Name field.

            ec.create_tags(
                Resources=to_tag[retention_days],
                Tags=[
                    {'Key': 'Name', 'Value': dev_attachment}

**Comment by cmachler** [comment]
Good catch, never tested instances with multiple volumes. Will take a look at it when I have free time.

**Comment by cmachler** [comment]
@pasea try now, I created a separate collection for creating mount point tags.

**Comment by pasea** [comment]
Works like a charm.  Thank you.
