### ISSUE TITLE
How to change backup snapshot name ?

### ISSUE THREAD

**Issue by pyephyoeaung** [cmachler/aws-lambda-ebs-backups#11]
Hi , I 'm not a programmer . I used this script in our project.
I want to change snapshot name to volume name . 
How can I change ?

**Comment by cmachler** [comment]
Hi,

This doc might help:

http://boto3.readthedocs.io/en/latest/reference/services/ec2.html#snapshot

Along with changing this section in the backup script:

https://github.com/cmachler/aws-lambda-ebs-backups/blob/master/lambda-ebs-backup.py#L91-L94

Regards,

Chris
